parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: edusoho
    database_user: root
    database_password: 'abby0329'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: slcx9foex8g4kc8koko080coc00c8oo
    user_partner: none